# Generated by Django 4.0.3 on 2022-03-24 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_equipement_ensemble_equipement_tracteur_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Heure de la validation')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Heure de la validation')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Heure de la validation')),
                ('montant_ht', models.FloatField(default=0, verbose_name='Montant HT')),
                ('montant_tva', models.FloatField(default=0, verbose_name='Montant TVA')),
                ('montant_poids', models.FloatField(default=0, verbose_name='Volume')),
                ('montant_ttc', models.FloatField(default=0, verbose_name='Remise TTC')),
                ('facture', models.BooleanField(default=False, verbose_name='Facturé?')),
                ('reference_client', models.CharField(blank=True, max_length=64, null=True, verbose_name='Référence client')),
                ('reference_externe', models.CharField(blank=True, max_length=64, null=True, verbose_name='Référence externe')),
                ('external_id', models.CharField(max_length=16, verbose_name='Identifiant')),
                ('etat', models.CharField(choices=[('draft', 'Brouillon'), ('cancel', 'Annulé'), ('ongoing', 'En cours'), ('done', 'Terminé')], db_index=True, default='draft', max_length=10, verbose_name='Etat')),
                ('accepted_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_etapes', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(limit_choices_to={'actif': True}, on_delete=django.db.models.deletion.PROTECT, related_name='ventes', to='base.client', verbose_name='Client')),
                ('conducteur', models.ForeignKey(limit_choices_to={'actif': True}, on_delete=django.db.models.deletion.PROTECT, to='base.conducteur', verbose_name='Conducteur')),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_etapes', to=settings.AUTH_USER_MODEL)),
                ('finished_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finished_etapes', to=settings.AUTH_USER_MODEL)),
                ('flotte', models.ForeignKey(limit_choices_to={'actif': True}, on_delete=django.db.models.deletion.PROTECT, to='base.flotte', verbose_name='Flotte')),
                ('started_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='started_etapes', to=settings.AUTH_USER_MODEL)),
                ('tournee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.tournee', verbose_name='Tournée')),
                ('tracteur', models.ForeignKey(blank=True, limit_choices_to={'actif': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.equipement', verbose_name='Camion')),
            ],
            options={
                'verbose_name_plural': 'Etapes de tournée',
            },
        ),
        migrations.DeleteModel(
            name='Trancon',
        ),
    ]
